# Generated automatically from Makefile.in by configure.
SUBDIRS = client_table miniserver net service_table util



all:	
	(for d in $(SUBDIRS); do $(MAKE) -C $$d all; done) || exit 1;

clean:	
	(for d in $(SUBDIRS); do $(MAKE) -C $$d clean ; done) || exit 1;

install:
#	cd upnp/sample/linux-igd; $(MAKE) install


