# Generated automatically from Makefile.in by configure.

SUBDIRS = linuxigd-1.0

all:	
	(for d in $(SUBDIRS); do $(MAKE) -C $$d all; done) || exit 1;

clean:	
	(for d in $(SUBDIRS); do $(MAKE) -C $$d clean ; done) || exit 1;

install:
	(for d in $(SUBDIRS); do $(MAKE) -C $$d install ; done) || exit 1;


