TOPDIR := .

#SUBDIRS = src conf/Dllso_example
SUBDIRS = src conf/Dllso_example conf

O_TARGET =
SOURCES =

bin_PROG =

test_PROG =


CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS =
LDLIBS  =

include $(TOPDIR)/rules.mk

