TOPDIR := ../..

SUBDIRS = conf msg str

O_TARGET =

SOURCES =

#**********************
#bin_PROG = prog
#prog_SOURCE = prog.c xxx.c yyy.c
#prog_LIB = prog.o xxx.a yyy.a
#**********************
bin_PROG =

#**********************
#test_PROG = mytest
#mytestg_SOURCE = prog.c xxx.c yyy.c
#mytest_LIB = prog.o xxx.a yyy.a
#**********************
test_PROG =

SHARED_LIB = libpublic.so
libpublic.so_LIB = conf/libconf.o msg/libmsgq.o str/libstr.o

CFLAGS =
DEFS   = 
INCLUDE = 

LDFLAGS =
LDLIBS  = 

include $(TOPDIR)/rules.mk
