/* This file is automatically generated by configure.  Do not modify by hand. */
/* Define if compiling with the mibII/vacm_vars module files.  */
#define USING_MIBII_VACM_VARS_MODULE 1
 
/* Define if compiling with the dlink module files.  */
#define USING_DLINK_MODULE 1
 
/* Define if compiling with the applicationRuleTable module files.  */
#define USING_APPLICATIONRULETABLE_MODULE 1
 
/* Define if compiling with the dlkEnterpriseClientListTable module files.  */
#define USING_DLKENTERPRISECLIENTLISTTABLE_MODULE 1
 
/* Define if compiling with the dlkEnterpriseReservationTable module files.  */
#define USING_DLKENTERPRISERESERVATIONTABLE_MODULE 1
 
/* Define if compiling with the dlkEnterpriseScanListTable module files.  */
#define USING_DLKENTERPRISESCANLISTTABLE_MODULE 1
 
/* Define if compiling with the macFilterTable module files.  */
#define USING_MACFILTERTABLE_MODULE 1
 
/* Define if compiling with the portForwardingTable module files.  */
#define USING_PORTFORWARDINGTABLE_MODULE 1
 
/* Define if compiling with the scheduleRuleTable module files.  */
#define USING_SCHEDULERULETABLE_MODULE 1
 
/* Define if compiling with the virtualServerTable module files.  */
#define USING_VIRTUALSERVERTABLE_MODULE 1
 
/* Define if compiling with the webFilterTable module files.  */
#define USING_WEBFILTERTABLE_MODULE 1
 
/* Define if compiling with the util_funcs module files.  */
#define USING_UTIL_FUNCS_MODULE 1
 
/* Define if compiling with the mibII/vacm_context module files.  */
#define USING_MIBII_VACM_CONTEXT_MODULE 1
 
