/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("vacm_vars")) init_vacm_vars();
  if (should_init("dlink")) init_dlink();
  if (should_init("applicationRuleTable")) init_applicationRuleTable();
  if (should_init("dlkEnterpriseClientListTable")) init_dlkEnterpriseClientListTable();
  if (should_init("dlkEnterpriseReservationTable")) init_dlkEnterpriseReservationTable();
  if (should_init("dlkEnterpriseScanListTable")) init_dlkEnterpriseScanListTable();
  if (should_init("macFilterTable")) init_macFilterTable();
  if (should_init("portForwardingTable")) init_portForwardingTable();
  if (should_init("scheduleRuleTable")) init_scheduleRuleTable();
  if (should_init("virtualServerTable")) init_virtualServerTable();
  if (should_init("webFilterTable")) init_webFilterTable();
  if (should_init("vacm_context")) init_vacm_context();
