/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.4 2005/04/26 22:13:28 rstory Exp $
 *
 * $Id: portForwardingTable.h,v 1.1.1.1 2007/08/30 10:28:09 roy Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef PORTFORWARDINGTABLE_H
#define PORTFORWARDINGTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index portForwardingIndex is internal */

    typedef struct portForwardingTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER = ASN_INTEGER */
        long            portForwardingIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   portForwardingList[65535];
        long            portForwardingList_len;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } portForwardingTable_context;

/*************************************************************
 * function declarations
 */
    void            init_portForwardingTable(void);
    void            initialize_table_portForwardingTable(void);
    const portForwardingTable_context
        *portForwardingTable_get_by_idx(netsnmp_index *);
    const portForwardingTable_context
        *portForwardingTable_get_by_idx_rs(netsnmp_index *,
                                           int row_status);
    int             portForwardingTable_get_value(netsnmp_request_info *,
                                                  netsnmp_index *,
                                                  netsnmp_table_request_info
                                                  *);


/*************************************************************
 * oid declarations
 */
    extern oid      portForwardingTable_oid[];
    extern size_t   portForwardingTable_oid_len;

#define portForwardingTable_TABLE_OID 1,3,6,1,4,1,171,1,5,7,1

/*************************************************************
 * column number definitions for table portForwardingTable
 */
#define COLUMN_PORTFORWARDINGINDEX 1
#define COLUMN_PORTFORWARDINGLIST 2
#define portForwardingTable_COL_MIN 1
#define portForwardingTable_COL_MAX 2

    /*
     * comment out the following line if you don't handle SET-REQUEST for portForwardingTable 
     */
#define portForwardingTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define portForwardingTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define portForwardingTable_IDX2

#ifdef portForwardingTable_SET_HANDLING

    int            
        portForwardingTable_extract_index(portForwardingTable_context *
                                          ctx, netsnmp_index * hdr);

    void            portForwardingTable_set_reserve1(netsnmp_request_group
                                                     *);
    void            portForwardingTable_set_reserve2(netsnmp_request_group
                                                     *);
    void            portForwardingTable_set_action(netsnmp_request_group
                                                   *);
    void            portForwardingTable_set_commit(netsnmp_request_group
                                                   *);
    void            portForwardingTable_set_free(netsnmp_request_group *);
    void            portForwardingTable_set_undo(netsnmp_request_group *);

    portForwardingTable_context
        *portForwardingTable_duplicate_row(portForwardingTable_context *);
    netsnmp_index 
        *portForwardingTable_delete_row(portForwardingTable_context *);

    int            
        portForwardingTable_can_delete(portForwardingTable_context *
                                       undo_ctx,
                                       portForwardingTable_context *
                                       row_ctx,
                                       netsnmp_request_group * rg);


#ifdef portForwardingTable_ROW_CREATION
    portForwardingTable_context
        *portForwardingTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef portForwardingTable_IDX2
    portForwardingTable_context *portForwardingTable_get(const char *name,
                                                         int len);
#endif

#ifdef __cplusplus
}
#endif
#endif /** PORTFORWARDINGTABLE_H */
