/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.4 2005/04/26 22:13:28 rstory Exp $
 *
 * $Id: webFilterTable.h,v 1.1.1.1 2007/08/30 10:28:09 roy Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef WEBFILTERTABLE_H
#define WEBFILTERTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index webFilterIndex is internal */

    typedef struct webFilterTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER = ASN_INTEGER */
        long            webFilterIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   webFilterList[65535];
        long            webFilterList_len;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } webFilterTable_context;

/*************************************************************
 * function declarations
 */
    void            init_webFilterTable(void);
    void            initialize_table_webFilterTable(void);
    const webFilterTable_context *webFilterTable_get_by_idx(netsnmp_index
                                                            *);
    const webFilterTable_context
        *webFilterTable_get_by_idx_rs(netsnmp_index *, int row_status);
    int             webFilterTable_get_value(netsnmp_request_info *,
                                             netsnmp_index *,
                                             netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      webFilterTable_oid[];
    extern size_t   webFilterTable_oid_len;

#define webFilterTable_TABLE_OID 1,3,6,1,4,1,171,1,5,7,2

/*************************************************************
 * column number definitions for table webFilterTable
 */
#define COLUMN_WEBFILTERINDEX 1
#define COLUMN_WEBFILTERLIST 2
#define webFilterTable_COL_MIN 1
#define webFilterTable_COL_MAX 2

    /*
     * comment out the following line if you don't handle SET-REQUEST for webFilterTable 
     */
#define webFilterTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define webFilterTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define webFilterTable_IDX2

#ifdef webFilterTable_SET_HANDLING

    int             webFilterTable_extract_index(webFilterTable_context *
                                                 ctx, netsnmp_index * hdr);

    void            webFilterTable_set_reserve1(netsnmp_request_group *);
    void            webFilterTable_set_reserve2(netsnmp_request_group *);
    void            webFilterTable_set_action(netsnmp_request_group *);
    void            webFilterTable_set_commit(netsnmp_request_group *);
    void            webFilterTable_set_free(netsnmp_request_group *);
    void            webFilterTable_set_undo(netsnmp_request_group *);

    webFilterTable_context
        *webFilterTable_duplicate_row(webFilterTable_context *);
    netsnmp_index  *webFilterTable_delete_row(webFilterTable_context *);

    int             webFilterTable_can_delete(webFilterTable_context *
                                              undo_ctx,
                                              webFilterTable_context *
                                              row_ctx,
                                              netsnmp_request_group * rg);


#ifdef webFilterTable_ROW_CREATION
    webFilterTable_context *webFilterTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef webFilterTable_IDX2
    webFilterTable_context *webFilterTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
}
#endif
#endif /** WEBFILTERTABLE_H */
