/* This file is automatically generated by the configuration system
 * Any changes will be lost when the configuration is saved as this
 * file will be rewritten. */
#include <mrd/mrd.h>

extern "C" mrd_module *mrd_module_init_mld(void *, mrd *);

void mrd::add_static_modules() {
	m_static_modules["mld"] = &mrd_module_init_mld;
}
